import { Router, Response } from 'express'
import { z } from 'zod'
import { prisma } from '../prisma'
import { authenticate, requireAdmin, AuthRequest } from '../middleware/authenticate'

// Same visibility model as empanelments.ts — client-relationship-level data,
// visible to everyone.
const router = Router()
router.use(authenticate)

export const TENDER_STATUSES = ['Identified', 'Preparing', 'Submitted', 'Under Evaluation', 'Won', 'Lost'] as const

const tenderInclude = {
  client: { select: { id: true, clientName: true } },
  createdByUser: { select: { id: true, userName: true, email: true } },
} as const

router.get('/', async (_req, res) => {
  const tenders = await prisma.tender.findMany({
    where: { deletedAt: null },
    include: tenderInclude,
    orderBy: { createdAt: 'desc' },
  })
  res.json({ tenders })
})

// tenderNo is entered manually — it's issued by the tendering authority, not
// generated by this system.
const createSchema = z.object({
  tenderNo: z.string().min(1, 'Tender number is required.'),
  clientId: z.string().min(1),
  submissionDate: z.coerce.date().optional(),
  value: z.coerce.number().optional(),
  status: z.enum(TENDER_STATUSES).optional(),
})

router.post('/', async (req: AuthRequest, res: Response): Promise<void> => {
  const parse = createSchema.safeParse(req.body)
  if (!parse.success) {
    res.status(400).json({ error: parse.error.issues[0]?.message ?? 'Invalid tender data.' })
    return
  }
  const d = parse.data
  try {
    const tender = await prisma.tender.create({
      data: {
        tenderNo: d.tenderNo.trim(),
        clientId: d.clientId,
        submissionDate: d.submissionDate ?? null,
        value: d.value ?? null,
        status: d.status ?? 'Identified',
        createdByUserId: req.userId!,
      },
      include: tenderInclude,
    })
    res.status(201).json({ tender })
  } catch {
    res.status(400).json({ error: 'Could not create tender. Does the client exist?' })
  }
})

const updateSchema = z.object({
  submissionDate: z.coerce.date().nullable().optional(),
  value: z.coerce.number().nullable().optional(),
  status: z.enum(TENDER_STATUSES).optional(),
})

router.patch('/:id', async (req: AuthRequest, res: Response): Promise<void> => {
  const parse = updateSchema.safeParse(req.body)
  if (!parse.success) {
    res.status(400).json({ error: 'Invalid update data.' })
    return
  }
  const existing = await prisma.tender.findFirst({ where: { id: String(req.params.id), deletedAt: null } })
  if (!existing) {
    res.status(404).json({ error: 'Tender not found.' })
    return
  }
  const d = parse.data
  const data: Record<string, unknown> = {}
  if ('submissionDate' in d) data.submissionDate = d.submissionDate
  if ('value' in d) data.value = d.value
  if (d.status) data.status = d.status
  const tender = await prisma.tender.update({ where: { id: existing.id }, data, include: tenderInclude })
  res.json({ tender })
})

router.delete('/:id', requireAdmin, async (req: AuthRequest, res: Response): Promise<void> => {
  const existing = await prisma.tender.findFirst({ where: { id: String(req.params.id), deletedAt: null } })
  if (!existing) {
    res.status(404).json({ error: 'Tender not found.' })
    return
  }
  await prisma.tender.update({ where: { id: existing.id }, data: { deletedAt: new Date() } })
  res.json({ message: 'Tender deleted.' })
})

export default router
